/**
 * Predefined units for products and inventory management.
 */
export const PRODUCT_UNITS = [
  { value: "PCS", label: "Pieces (PCS)" },
  { value: "BOX", label: "Box (BOX)" },
  { value: "SET", label: "Set (SET)" },
  { value: "UNIT", label: "Unit (UNIT)" },
  { value: "KG", label: "Kilogram (KG)" },
  { value: "G", label: "Gram (G)" },
  { value: "M", label: "Meter (M)" },
  { value: "FT", label: "Feet (FT)" },
  { value: "PKT", label: "Packet (PKT)" },
  { value: "ROL", label: "Roll (ROL)" },
] as const;

export type ProductUnit = (typeof PRODUCT_UNITS)[number]["value"];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Puducherry",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
] as const;
